### ISSUE TITLE
win7 64位 家庭普通版，tunsafe1.4，1.5均APPcrash

### ISSUE THREAD

**Issue by 2018song** [hongwenjun/vps_setup#1]
APPCRASH
  应用程序名:	TunSafe.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5bbe1248
  故障模块名称:	TunSafe.exe
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5bbe1248
  异常代码:	c000001d
  异常偏移:	000000000000f9bd
  OS 版本:	6.1.7600.2.0.0.768.2
  区域设置 ID:	2052
  其他信息 1:	9b4e
  其他信息 2:	9b4ea178303605071ea294765227c765
  其他信息 3:	292b
  其他信息 4:	292b9bfbf2f10d4e4897ed3846ed0635

**Comment by hongwenjun** [comment]
这个杀毒软件有关吧，换台电脑试试，把杀毒软件关了

**Comment by 2018song** [comment]
没有安装任何杀毒软件，心好累
