### ISSUE TITLE
wireguard安装脚本的优化（建议）

### ISSUE THREAD

**Issue by playNoA** [hongwenjun/vps_setup#14]
我今天尝试了使用这个脚本去一台新的vps上安装，发现有个悖论:smile:（解压winrar需要winrar.exe，而它在winrar.rar中:joy:）
![image](https://user-images.githubusercontent.com/7344597/78417750-c0686e80-7667-11ea-9e65-13bea36ea142.png)
一般vps的centos7都是minimal版本，都是不包含wget的，如果我不装wget，怎么下载脚本呢？
获取脚本是否改成`curl -o`更适合呢？curl是包含在minimal版本中的:smirk:

**Comment by hongwenjun** [comment]
```bash
bash <(curl -L -s https://git.io/vps.sh)
# curl脚本可以使用菜单，方便选择 # wget脚本是静默安装
# wget -qO- git.io/vps.sh | bash
```
或者 yum install wget 先 安装一下。测试了很多vps 一般都是有wget 没 curl 的多
