### ISSUE TITLE
bash wgmtu

### ISSUE THREAD

**Issue by iambonboncat** [hongwenjun/vps_setup#6]
bash wgmtu

**Comment by dahuziqi** [comment]
无论是扫描二维码还是导入配置文件，wireguard在手机和电脑上都无法与服务器连接。

**Comment by hongwenjun** [comment]
wireguard 支持 KVM虚拟主机，不支持 ovz主机
服务器端 输入  wg 命令，看看服务端有没正确安装。
客户端使用tunsafe 如果链接是绿色指示灯，就说明正确连接了。
连接了不能科学上网，这个就要看RP了，和本地电信商关系挺大的
