### ISSUE TITLE
安装好后 怎么查看SS 跟V2RAY的配置

### ISSUE THREAD

**Issue by lone1985** [hongwenjun/vps_setup#7]
我第一次安装完成后没有记录，以后怎么查看SS 跟V2RAY的配置

**Comment by legon752** [comment]
你是?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: lone1985 <notifications@github.com>
发送时间: Monday, April 8, 2019 3:24:43 PM
收件人: hongwenjun/vps_setup
抄送: Subscribed
主题: [hongwenjun/vps_setup] 安装好后 怎么查看SS 跟V2RAY的配置 (#7)


我第一次安装完成后没有记录，以后怎么查看SS 跟V2RAY的配置

―

**Comment by hongwenjun** [comment]
会把安装信息保存在  v2ray_ss.log 中
cat v2ray_ss.log
或者 这个命令也可以  bash <(curl -L -s https://git.io/v2ray.ss)    这个脚本再次执行，默认不修改，只显示之前的
如果想需改配置信息，可以后面加  setup 参数
:: 命令 bash <(curl -L -s https://git.io/v2ray.ss) setup 设置修改端口密码和UUID

**Comment by lone1985** [comment]
谢谢了
