### ISSUE TITLE
WireGuard刚安装好能正常使用，但是重启VPS之后能连上，但是无法上网

### ISSUE THREAD

**Issue by vincywindy** [hongwenjun/vps_setup#9]
WireGuard刚安装好能正常使用，但是重启VPS之后能连上，无法上网

**Comment by vincywindy** [comment]
查询日志也没有任何错误，系统是Debain9

**Comment by vincywindy** [comment]
卸载脚本后重新安装，又能连上，但是一旦VPS发生重启，Wiregurd就变成能连上却上不了网的状态

**Comment by hongwenjun** [comment]
apt install nginx 
http://10.0.0.1
ping 10.0.0.1 
如果能访问和ping到，软件安装就没问题。
可以观看视频，再在vpn局域网，再装个SS试试

**Comment by vincywindy** [comment]
能ping通，10.0.0.1也能访问，但是就是重启了vps之后，就不能访问其他网页了，重启vps之前能够正常访问，用SS+kcp的方案可以连上网，但是访问不了10.0.0.1

**Comment by hongwenjun** [comment]
> 能ping通，10.0.0.1也能访问，但是就是重启了vps之后，就不能访问其他网页了，重启vps之前能够正常访问，用SS+kcp的方案可以连上网，但是访问不了10.0.0.1

软件安装没问题，你可以看视频演示是怎么使用的
wg+ss 
wg+speed+udp2raw+ss
SS+kcp+udp2raw
很多钟使用场景

**Comment by vincywindy** [comment]
是的，安装使用都没问题，然后问题是出在vps重启之后，这个问题才会出现，而且仅仅wireguard变得可以连接但是无法访问服务器以外的网络，v2ray和ss都没有问题

**Comment by w311ang** [comment]
https://github.com/hongwenjun/vps_setup/blob/master/Wireguard/README.md#%E9%81%87%E5%88%B0wg%E8%BF%9E%E6%8E%A5%E4%B8%BB%E6%9C%BA%E8%80%8C%E6%B2%A1%E6%9C%89%E6%B5%81%E9%87%8F%E4%BD%BF%E7%94%A8-ip-addr-%E5%91%BD%E4%BB%A4%E6%A3%80%E6%9F%A5vps%E7%BD%91%E5%8D%A1%E6%98%AF%E5%90%A6%E6%98%AFensx%E5%8F%82%E8%80%83%E4%B8%8B%E9%9D%A2%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E9%87%8D%E5%90%AF
